//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTADOR_ENDERECO_ESTOQUE
    {
        public int PREE_CD_ID { get; set; }
        public int PREN_CD_ID { get; set; }
        public int PREE_IN_OPERACAO { get; set; }
        public System.DateTime PREE_DT_OPERACAO { get; set; }
        public int OSPD_CD_ID { get; set; }
        public int PREE_IN_OPERACAO_CHECADA { get; set; }
        public string PREE_NM_VERIFICADO_POR { get; set; }
        public Nullable<System.DateTime> PREE_DT_VERIFICADO_EM { get; set; }
        public byte[] PREE_TX_OBSERVACOES { get; set; }
        public int PREE_IN_ATIVO { get; set; }
    
        public virtual ORDEM_SERVICO_PRODUTO ORDEM_SERVICO_PRODUTO { get; set; }
        public virtual PRESTADOR_ENDERECO PRESTADOR_ENDERECO { get; set; }
    }
}
